-- YueAgent MVP schema
-- Execute in Supabase SQL Editor

create table if not exists public.questionnaires (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  answers jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.questionnaires
  add column if not exists created_at timestamptz not null default now();

alter table public.questionnaires
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  user1_id uuid not null,
  user2_id text not null,
  score integer not null,
  reason_json jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_matches_user1_created_at
  on public.matches (user1_id, created_at desc);

-- Deduplicate old questionnaire rows before adding unique constraint.
with ranked as (
  select
    id,
    row_number() over (
      partition by user_id
      order by updated_at desc, id desc
    ) as rn
  from public.questionnaires
)
delete from public.questionnaires q
using ranked r
where q.id = r.id
  and r.rn > 1;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'questionnaires_user_id_key'
      and conrelid = 'public.questionnaires'::regclass
  ) then
    alter table public.questionnaires
      add constraint questionnaires_user_id_key unique (user_id);
  end if;
end;
$$;

-- Keep updated_at fresh
create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  if to_jsonb(new) ? 'updated_at' then
    new := jsonb_populate_record(new, jsonb_build_object('updated_at', now()));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_questionnaires_updated_at on public.questionnaires;
create trigger trg_questionnaires_updated_at
before update on public.questionnaires
for each row
execute procedure public.set_current_timestamp_updated_at();

-- RLS
alter table public.questionnaires enable row level security;
alter table public.matches enable row level security;

-- Users can read/write their own questionnaire
drop policy if exists questionnaires_select_own on public.questionnaires;
create policy questionnaires_select_own
  on public.questionnaires
  for select
  using (auth.uid() = user_id);

drop policy if exists questionnaires_insert_own on public.questionnaires;
create policy questionnaires_insert_own
  on public.questionnaires
  for insert
  with check (auth.uid() = user_id);

drop policy if exists questionnaires_update_own on public.questionnaires;
create policy questionnaires_update_own
  on public.questionnaires
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can read their own match history
drop policy if exists matches_select_own on public.matches;
create policy matches_select_own
  on public.matches
  for select
  using (auth.uid() = user1_id);
